vich_uploader:
    db_driver: orm

    mappings:
        media_book:
            uri_prefix: /upload
            upload_destination: '%kernel.project_dir%/public/upload'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
